# Generated by Django 5.2.13 on 2026-05-01 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20)),
                ('topic_number', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('source', models.CharField(default='manifest', max_length=80)),
            ],
            options={
                'ordering': ('subject_code', 'topic_number', 'name'),
                'unique_together': {('subject_code', 'topic_number', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.CharField(max_length=120)),
                ('subject_code', models.CharField(max_length=20)),
                ('session', models.CharField(max_length=20)),
                ('component', models.CharField(max_length=20)),
                ('paper_number', models.PositiveIntegerField()),
                ('question_number', models.PositiveIntegerField()),
                ('marks', models.PositiveIntegerField(blank=True, null=True)),
                ('source_qp_path', models.CharField(max_length=500)),
                ('source_ms_path', models.CharField(blank=True, max_length=500)),
                ('split_qp_path', models.CharField(blank=True, max_length=500)),
                ('split_ms_path', models.CharField(blank=True, max_length=500)),
                ('qp_start_page_raw', models.CharField(max_length=20)),
                ('ms_start_page_raw', models.CharField(blank=True, max_length=20)),
                ('qp_review_status', models.CharField(choices=[('not_required', 'Not required'), ('needs_review', 'Needs review'), ('reviewed', 'Reviewed')], default='not_required', max_length=20)),
                ('ms_review_status', models.CharField(choices=[('not_required', 'Not required'), ('needs_review', 'Needs review'), ('reviewed', 'Reviewed')], default='not_required', max_length=20)),
                ('review_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='libraries.library')),
                ('topics', models.ManyToManyField(blank=True, to='catalog.topic')),
            ],
            options={
                'ordering': ('paper_number', 'question_number', 'session', 'component'),
                'unique_together': {('library', 'exam_code', 'question_number')},
            },
        ),
    ]
