# Generated by Django 5.2.13 on 2026-05-01 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('mode', models.CharField(choices=[('full_paper', 'Full paper'), ('topic', 'Topic based'), ('question_number', 'Question number based'), ('manual', 'Manual selection')], max_length=30)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('settings_snapshot', models.JSONField(blank=True, default=dict)),
                ('exam_pdf_path', models.CharField(blank=True, max_length=500)),
                ('markscheme_pdf_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_exams', to='libraries.library')),
                ('questions', models.ManyToManyField(blank=True, to='catalog.question')),
            ],
        ),
    ]
