# Generated by Django 5.2.13 on 2026-05-08 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0004_appsettings_app_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=8)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('layout_settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='MCQSubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('topic__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MCQExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('mode', models.CharField(choices=[('full_paper', 'Full paper'), ('topic', 'Topic based'), ('manual', 'Manual selection')], max_length=30)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('settings_snapshot', models.JSONField(blank=True, default=dict)),
                ('student_pdf_path', models.CharField(blank=True, max_length=600)),
                ('teacher_pdf_path', models.CharField(blank=True, max_length=600)),
                ('answer_key_pdf_path', models.CharField(blank=True, max_length=600)),
                ('metadata_report_path', models.CharField(blank=True, max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_exams', to='libraries.library')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='MCQImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('question', 'Question image'), ('option', 'Option image'), ('table_cell', 'Table cell image'), ('other', 'Other')], default='other', max_length=30)),
                ('original_name', models.CharField(max_length=220)),
                ('file_path', models.CharField(max_length=600)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_assets', to='libraries.library')),
            ],
            options={
                'ordering': ('-created_at', 'original_name'),
            },
        ),
        migrations.CreateModel(
            name='MCQOptionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('equation', 'Equation')], max_length=20)),
                ('text', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option_blocks', to='mcq.mcqimageasset')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='mcq.mcqoption')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=220)),
                ('subject', models.CharField(default='Physics', max_length=80)),
                ('syllabus', models.CharField(default='9702', max_length=40)),
                ('exam_code', models.CharField(blank=True, max_length=120)),
                ('paper_code', models.CharField(blank=True, max_length=40)),
                ('session', models.CharField(blank=True, max_length=40)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('variant', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(blank=True, max_length=180)),
                ('source_question_number', models.CharField(blank=True, max_length=30)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('time_estimate_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=40)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('needs_review', 'Needs review'), ('verified', 'Verified'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('teacher_notes', models.TextField(blank=True)),
                ('layout_preset', models.CharField(choices=[('standard', 'Standard text with options below'), ('image_above', 'Image above options'), ('text_image_side', 'Text and image side by side'), ('image_only', 'Image-only question'), ('option_grid', 'Image option grid'), ('table_options', 'Table options'), ('compact', 'Compact exam style')], default='standard', max_length=40)),
                ('option_layout', models.CharField(choices=[('single', 'Single column'), ('two_column', 'Two columns'), ('four_column', 'Four columns'), ('grid', 'Image grid'), ('table', 'Table')], default='single', max_length=40)),
                ('layout_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='libraries.library')),
                ('subtopics', models.ManyToManyField(blank=True, related_name='questions', to='mcq.mcqsubtopic')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='mcqoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='mcq.mcqquestion'),
        ),
        migrations.CreateModel(
            name='MCQQuestionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('table', 'Table'), ('note', 'Note'), ('mixed', 'Mixed')], max_length=20)),
                ('text', models.TextField(blank=True)),
                ('table_data', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_blocks', to='mcq.mcqimageasset')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='mcq.mcqquestion')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MCQTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_tags', to='libraries.library')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('library', 'name')},
            },
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='mcq.mcqtag'),
        ),
        migrations.CreateModel(
            name='MCQTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_topics', to='libraries.library')),
            ],
            options={
                'ordering': ('name',),
                'unique_together': {('library', 'name')},
            },
        ),
        migrations.AddField(
            model_name='mcqsubtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='mcq.mcqtopic'),
        ),
        migrations.AddField(
            model_name='mcqquestion',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='questions', to='mcq.mcqtopic'),
        ),
        migrations.AlterUniqueTogether(
            name='mcqoption',
            unique_together={('question', 'label')},
        ),
        migrations.CreateModel(
            name='MCQExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('option_order', models.JSONField(blank=True, default=list)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='mcq.mcqexam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_links', to='mcq.mcqquestion')),
            ],
            options={
                'ordering': ('order', 'id'),
                'unique_together': {('exam', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='mcqsubtopic',
            unique_together={('topic', 'name')},
        ),
    ]
