# Generated by Django 5.2.13 on 2026-05-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqquestionblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('equation', 'Equation'), ('table', 'Table'), ('note', 'Note'), ('mixed', 'Mixed')], max_length=20),
        ),
    ]
