# Generated by Django 5.2.13 on 2026-05-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('root_path', models.CharField(max_length=500)),
                ('source_papers_path', models.CharField(default='source_papers', max_length=500)),
                ('question_bank_path', models.CharField(default='QuestionBank', max_length=500)),
                ('generated_exams_path', models.CharField(default='generated_exams', max_length=500)),
                ('manifests_path', models.CharField(default='manifests', max_length=500)),
                ('naming_preset', models.CharField(default='cambridge', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
