# Generated by Django 5.2.13 on 2026-05-01 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_manifest_path', models.CharField(blank=True, max_length=500)),
                ('default_source_root', models.CharField(blank=True, max_length=500)),
                ('default_output_root', models.CharField(blank=True, max_length=500)),
                ('default_generated_exams_root', models.CharField(blank=True, max_length=500)),
                ('paper_marks', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='libraries.library')),
            ],
        ),
    ]
