# Generated by Django 5.2.13 on 2026-05-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_appsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='pdf_mask_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
