# Generated by Django 5.2.13 on 2026-05-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_appsettings_pdf_mask_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='app_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
